# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/mem_2kx16/mem_2kx16.xci
# IP: The module: 'mem_2kx16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/mem_2kx16/mem_2kx16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_2kx16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/mem_2kx16/mem_2kx16.xci
# IP: The module: 'mem_2kx16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/mem_2kx16/mem_2kx16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_2kx16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
