# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.cache/wt [current_project]
set_property parent.project_path D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/interface/sys_bus_if.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/interface/axi4_if.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/interface/gpio_if.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/axi4_slave.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/red_pitaya_dfilt1.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/red_pitaya_pll.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/sys_bus_interconnect.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_pwm.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/sys_bus_stub.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/prj/v0.94/rtl/red_pitaya_ps.sv
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/prj/v0.94/rtl/red_pitaya_top.sv
}
read_verilog -library xil_defaultlib {
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/axi_wr_fifo.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_pid_block.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_asg_ch.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/axi_master.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_scope.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_hk.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_pid.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_asg.v
  D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_ams.v
}
add_files D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_processing_system7_0/system_processing_system7_0.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xdc]
set_property used_in_implementation false [get_files -all D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/constrs_1/imports/sdc/red_pitaya.xdc
set_property used_in_implementation false [get_files D:/proj/velograph/rp_test/fpga/prj/v0.94/project/redpitaya.srcs/constrs_1/imports/sdc/red_pitaya.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top red_pitaya_top -part xc7z010clg400-1


write_checkpoint -force -noxdef red_pitaya_top.dcp

catch { report_utilization -file red_pitaya_top_utilization_synth.rpt -pb red_pitaya_top_utilization_synth.pb }
