# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs/clocks.xdc

# XDC: imports/constrs/sparrow5_top.xdc

# Block Designs: bd/sparrow_ps/sparrow_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps || ORIG_REF_NAME==sparrow_ps} -quiet] -quiet

# IP: bd/sparrow_ps/ip/sparrow_ps_processing_system7_0_0/sparrow_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps_processing_system7_0_0 || ORIG_REF_NAME==sparrow_ps_processing_system7_0_0} -quiet] -quiet

# IP: bd/sparrow_ps/ip/sparrow_ps_rst_ps7_0_50M_0/sparrow_ps_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps_rst_ps7_0_50M_0 || ORIG_REF_NAME==sparrow_ps_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sparrow_ps/ip/sparrow_ps_xadc_wiz_0_0/sparrow_ps_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps_xadc_wiz_0_0 || ORIG_REF_NAME==sparrow_ps_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/sparrow_ps/ip/sparrow_ps_xbar_0/sparrow_ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps_xbar_0 || ORIG_REF_NAME==sparrow_ps_xbar_0} -quiet] -quiet

# IP: bd/sparrow_ps/ip/sparrow_ps_ps7_0_axi_periph_0/sparrow_ps_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps_ps7_0_axi_periph_0 || ORIG_REF_NAME==sparrow_ps_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sparrow_ps/ip/sparrow_ps_auto_pc_0/sparrow_ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sparrow_ps_auto_pc_0 || ORIG_REF_NAME==sparrow_ps_auto_pc_0} -quiet] -quiet

# XDC: bd/sparrow_ps/sparrow_ps_ooc.xdc
