# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 6
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.cache/wt [current_project]
set_property parent.project_path D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/proj/umka2/xil/octopuz3a/my_ip/axi_udef_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs D:/proj/velograph/sparrow_w/xil/sparrow/sparrow.srcs/sources_1 [current_fileset]
read_verilog -library xil_defaultlib {
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/axi/axi_slave.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/utrk/sepia_time.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/hdl/sparrow_ps_wrapper.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/sparrow_ps_v.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/dac/dac_data_out.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/lib/spi_master3p.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/u_spi.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/dac/u_dac.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/dac/phase_acc.v
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/sparrow5_top.v
}
read_vhdl -library xil_defaultlib {
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/fft/fp23_op/fp_m1_pkg.vhd
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/fft/sp_op/reduce_pack.vhd
  D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/imports/rtl/fft/sp_op/sp_int2str_pkg.vhd
}
add_files D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/sparrow_ps.bd
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_processing_system7_0_0/sparrow_ps_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_rst_ps7_0_50M_0/sparrow_ps_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_rst_ps7_0_50M_0/sparrow_ps_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_rst_ps7_0_50M_0/sparrow_ps_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_xadc_wiz_0_0/sparrow_ps_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_xadc_wiz_0_0/sparrow_ps_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_xbar_0/sparrow_ps_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/ip/sparrow_ps_auto_pc_0/sparrow_ps_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/bd/sparrow_ps/sparrow_ps_ooc.xdc]

read_ip -quiet D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/mem_2kx16/mem_2kx16.xci
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/mem_2kx16/mem_2kx16_ooc.xdc]

read_ip -quiet D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/pll24_80/pll24_80.xci
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/pll24_80/pll24_80_board.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/pll24_80/pll24_80.xdc]
set_property used_in_implementation false [get_files -all d:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/sources_1/ip/pll24_80/pll24_80_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/constrs_1/imports/constrs/clocks.xdc
set_property used_in_implementation false [get_files D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/constrs_1/imports/constrs/clocks.xdc]

read_xdc D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/constrs_1/imports/constrs/sparrow5_top.xdc
set_property used_in_implementation false [get_files D:/proj/velograph/sparrow_w/xil/sparrow5/sparrow5.srcs/constrs_1/imports/constrs/sparrow5_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sparrow5_top -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sparrow5_top.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file sparrow5_top_utilization_synth.rpt -pb sparrow5_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
