### create_generated_clock -name u_us/o_rdac_kus_clk -source [get_pins pll1/inst/plle2_adv_inst/CLKOUT2] -divide_by 2 [get_pins {u_us/rdac_kus_clk_reg[1]/Q}]
create_clock -period 12.500 -name VIRTUAL_clk_out1_pll24_80 -waveform {0.000 6.250}
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -clock_fall -min -add_delay 7.000 [get_ports {i_adc_dat_a[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -clock_fall -max -add_delay 9.000 [get_ports {i_adc_dat_a[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -min -add_delay 7.000 [get_ports {i_adc_dat_a[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -max -add_delay 9.000 [get_ports {i_adc_dat_a[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -clock_fall -min -add_delay 7.000 [get_ports {i_adc_dat_b[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -clock_fall -max -add_delay 9.000 [get_ports {i_adc_dat_b[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -min -add_delay 7.000 [get_ports {i_adc_dat_b[*]}]
###set_input_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -max -add_delay 9.000 [get_ports {i_adc_dat_b[*]}]
create_clock -period 6.250 -name VIRTUAL_clk_out2_pll24_80 -waveform {0.000 3.125}
###create_clock -period 50.000 -name VIRTUAL_u_us/o_rdac_kus_clk -waveform {0.000 25.000}
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -1.000 [get_ports {o_gen[*]}]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 5.000 [get_ports {o_gen[*]}]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -10.000 [get_ports o_mux_clk]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 40.000 [get_ports o_mux_clk]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -10.000 [get_ports o_mux_dat]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 40.000 [get_ports o_mux_dat]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -10.000 [get_ports o_pdac_a_cs]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 100.000 [get_ports o_pdac_a_cs]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -30.000 [get_ports o_pdac_b_cs]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 100.000 [get_ports o_pdac_b_cs]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -30.000 [get_ports o_pdac_clk]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 100.000 [get_ports o_pdac_clk]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -min -add_delay -30.000 [get_ports o_pdac_dat]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out2_pll24_80] -max -add_delay 100.000 [get_ports o_pdac_dat]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -min -add_delay -5.000 [get_ports rdac_kus_dat_a]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -max -add_delay 20.000 [get_ports rdac_kus_dat_a]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -min -add_delay -5.000 [get_ports rdac_kus_dat_a]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -max -add_delay 20.000 [get_ports rdac_kus_dat_a]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -min -add_delay -5.000 [get_ports rdac_kus_dat_b]
###set_output_delay -clock [get_clocks VIRTUAL_clk_out1_pll24_80] -max -add_delay 20.000 [get_ports rdac_kus_dat_b]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -min -add_delay -5.000 [get_ports rdac_kus_dat_b]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -max -add_delay 20.000 [get_ports rdac_kus_dat_b]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -min -add_delay -5.000 [get_ports rdac_kus_ncs_a]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -max -add_delay 20.000 [get_ports rdac_kus_ncs_a]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -min -add_delay -5.000 [get_ports rdac_kus_ncs_b]
###set_output_delay -clock [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] -clock_fall -max -add_delay 20.000 [get_ports rdac_kus_ncs_b]

###set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
###set_false_path -from [get_clocks clk_fpga_0] -to [list [get_clocks clk_fpga_1] [get_pins pll1/inst/clk_out2]]
###set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
###set_false_path -from [list [get_clocks clk_fpga_1] clk_out1_pll24_80pll1/clk_out2] -to [list [get_clocks clk_fpga_0] [get_pins pll1/clk_out1]]
###set_false_path -from [list [get_clocks clk_fpga_1] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks clk_fpga_0] [get_pins pll1/clk_out3]]
###set_false_path -from [list [get_clocks clk_fpga_1] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks clk_fpga_0] [get_pins pll1/clk_out1]]
###set_false_path -from [list [get_clocks clk_fpga_1] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks clk_fpga_0] [get_pins pll1/clk_out1] [get_pins pll1/inst/clk_out1]]
###set_false_path -from [list [get_clocks clk_fpga_1] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks clk_fpga_0] [get_pins pll1/clk_out1] [get_pins pll1/inst/clk_out1] [get_pins {pll1/inst/clk_out1 pll1/clk_out1}]]
###set_false_path -from [list [get_clocks clk_fpga_1] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks clk_fpga_0] [get_pins pll1/clk_out1] [get_pins pll1/inst/clk_out1] [get_pins {pll1/inst/clk_out1 pll1/clk_out3}]]

###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0]] -to [get_clocks *clk_out2*]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk[0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_u_us/o_rdac_kus_clk]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT1]]]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] [get_clocks VIRTUAL_clk_out2_pll24_80]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT1]]] [get_clocks *clk_out3*]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] [get_clocks VIRTUAL_clk_out2_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT1]]] [get_clocks *clk_out3*] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] [get_clocks VIRTUAL_clk_out2_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80]]
###set_false_path -from [list [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_pins i_ps/system_i/fclk0] [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT1]]] [get_clocks *clk_out3*] [get_clocks u_us/o_rdac_kus_clk] [get_clocks u_us/o_rdac_kus_clk]] -to [list [get_clocks *clk_out2*] [get_clocks *clk_out3*] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_u_us/o_rdac_kus_clk] [get_clocks VIRTUAL_clk_out2_pll24_80] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] [get_clocks VIRTUAL_clk_out1_pll24_80] [get_clocks VIRTUAL_u_us/o_rdac_kus_clk]]

###create_clock -period 25.000 -name clk40 -waveform {0.000 12.500} [get_nets clk40]
###create_generated_clock -source [get_ports i_clk24] -edges {1 2 3} -edge_shift {0.000 -8.333 -16.667} [get_pins pll1/clk_out3]
###create_clock -period 12.500 -name clk80 -waveform {0.000 6.250} [get_nets clk80]
###create_clock -period 6.250 -name clk160 -waveform {0.000 3.125} [get_nets clk160]
##set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
##set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
##set_false_path -from [get_clocks clk_fpga_1] -to [list [get_clocks clk_fpga_0] [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT1]]]]
###set_false_path -from [get_clocks [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT0]]] -to [get_clocks VIRTUAL_clk_out1_pll24_80]
set_false_path -from [get_clocks [get_clocks -of_objects [get_pins pll1/clk_out1]]] -to [get_clocks VIRTUAL_clk_out1_pll24_80]
set_false_path -from [get_clocks [get_clocks -of_objects [get_pins pll1/clk_out2]]] -to [get_clocks VIRTUAL_clk_out2_pll24_80]
##set_false_path -from [get_clocks VIRTUAL_clk_out1_pll24_80]  -to [get_clocks [get_clocks -of_objects [get_pins pll1/clk_out1]]]
set_false_path -from [get_clocks VIRTUAL_clk_out1_pll24_80] -to [get_clocks -of_objects [get_pins pll1/clk_out1]]

set_false_path -from [get_clocks -of_objects [get_pins i_ps/system_i/fclk*]] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk*]]
###set_false_path -from [get_clocks -of_objects [get_pins i_ps/system_i/fclk1]] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk0]]
###set_false_path -from [get_clocks -of_objects [get_pins i_ps/system_i/fclk1]] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk2]]
###set_false_path -from [get_clocks -of_objects [get_pins i_ps/system_i/fclk2]] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk0]]
###set_false_path -from [get_clocks -of_objects [get_pins i_ps/system_i/fclk2]] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk1]]

set_false_path -from [get_clocks -of_objects [get_pins i_ps/system_i/fclk*]] -to [get_clocks -of_objects [get_pins pll1/clk_out*]]
set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out*]] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk*]]


set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out1]] -to [get_clocks -of_objects [get_pins pll1/clk_out2]]
set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out1]] -to [get_clocks -of_objects [get_pins pll1/clk_out3]]
set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out2]] -to [get_clocks -of_objects [get_pins pll1/clk_out1]]
set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out2]] -to [get_clocks -of_objects [get_pins pll1/clk_out3]]
set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out3]] -to [get_clocks -of_objects [get_pins pll1/clk_out1]]
set_false_path -from [get_clocks -of_objects [get_pins pll1/clk_out3]] -to [get_clocks -of_objects [get_pins pll1/clk_out2]]



###create_clock -period 100.000 -name uu_sreg_we -waveform {0.000 50.000} [get_nets u_us/sregs_we_dat]
###set_false_path -from [get_clocks *sreg*] -to [get_clocks clk_fpga_0]
###set_false_path -from [get_clocks *sreg*] -to [get_clocks -of_objects [get_pins i_ps/system_i/fclk*]]

###create_clock -period 100.000 -name ug_sreg_we -waveform {0.000 50.000} [get_nets ugen/ug_set_sregs]

###create_generated_clock -name rdac_sck -source [get_pins pll1/inst/clk_out3] -divide_by 4 [get_nets {u_us/rdac_kus_clk[1]}]
###create_generated_clock -name rdac_sck -source [get_pins pll1/inst/clk_out3] -divide_by 4 -master_clock [get_clocks [list  [get_clocks -of_objects [get_pins pll1/inst/plle2_adv_inst/CLKOUT2]]]] [get_nets rdac_kus_clk]
###create_generated_clock -name rdac_sck -source [get_pins pll1/clk_out3] -divide_by 4 [get_nets rdac_kus_clk]

